name: rq-sigin-sync

on:
  workflow_dispatch:
  schedule:
    - cron: '30 9,10,16 * * *'
env:
  AESKEY: ${{ secrets.AESKEY }}
  RQ_EMAIL: ${{ secrets.RQ_EMAIL }}
  RQ_PASSWORD: ${{ secrets.RQ_PASSWORD }}
  WEBDAV_URL:  ${{ secrets.WEBDAV_URL }}
  WEBDAV_USERNAME:  ${{ secrets.WEBDAV_USERNAME }}
  WEBDAV_PASSWORD:  ${{ secrets.WEBDAV_PASSWORD }}
  QYWX_KEY:  ${{ secrets.QYWX_KEY }}
  
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.15
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.15"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run RQ Sigin Sync
      run: |
        python scripts/rq/rq_sgin.py
