name: rq-sigin-sync

on:
  workflow_dispatch:
  schedule:
    - cron: '30 9,10,16 * * *'
env:
  GITHUB_NAME: XiaoSiHwang
  GITHUB_EMAIL: 1009326507@qq.com
  AESKEY: ${{ secrets.AESKEY }}
  RQ_EMAIL: ${{ secrets.RQ_EMAIL }}
  RQ_PASSWORD: ${{ secrets.RQ_PASSWORD }}
  WEBDAV_URL:  ${{ secrets.WEBDAV_URL }}
  WEBDAV_USERNAME:  ${{ secrets.WEBDAV_USERNAME }}
  WEBDAV_PASSWORD:  ${{ secrets.WEBDAV_PASSWORD }}
  ## 通知推送配置
  # 企业微信机器人
  QYWX_KEY:  ${{ secrets.QYWX_KEY }}
  
  # 叮叮机器人
  DD_BOT_SECRET:  ${{ secrets.DD_BOT_SECRET }}
  DD_BOT_TOKEN:  ${{ secrets.DD_BOT_TOKEN }}

  
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.15
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.15"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run RQ Sigin Sync
      run: |
        python scripts/rq/rq_sgin.py
    - name: Push new cookie
      run: |
        git add .
        git commit -m 'update rq cookie' || echo "nothing to commit"
        git push || echo "nothing to push"
